appname = nebula-http-gateway
httpport = 8080
httpaddr = 0.0.0.0
runmode = dev
autorender = false
copyrequestbody = true
logspath = "./logs/"
loglevel = "info"
uploadspath = "./uploads/"
sqlitedbfilepath = "./tasks.db"
sessionkey = "common-nsid"
copyBatchSize = 1000
storageHostsMapping = nebula-storage-0.nebula.svc.cluster.local:192.168.1.10,nebula-storage-1.nebula.svc.cluster.local:192.168.1.11
